# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobj',
            name='myOther_var',
            field=models.FloatField(default=0.0),
        ),
    ]
