# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_myobj_myother_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobj',
            name='myVar',
            field=models.CharField(default='FU', max_length=200),
        ),
    ]
