# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160319_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobj',
            name='myVar',
            field=models.CharField(default='', max_length=200),
        ),
    ]
